version: '3.9'
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    image: my_mongodb:latest
    ports:
      - "27017:27017"
    container_name: my_mongodb_container
